spring:
  application:
    name: UrlShortener

  data:
    mongodb:
      uri: ${DATABASE_URL}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
